title: Your Health Snapshot
remote_theme: mmistakes/minimal-mistakes@4.24.0   # offizielle Version, kompatibel
description: "Snapshot-Seite für Ihre Health-Lösung"
baseurl: ""
url: "https://HealthSolutionsHub.github.io"
markdown: kramdown

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"

nav:
  - title: Startseite
    url: /
  - title: Fragebogen
    url: /questionnaire/
