title: "Your Health Snapshot"
email: your-email@example.com
description: "Health dashboard powered by Jekyll"
baseurl: "" # falls du die Seite auf Root hostest
url: "http://localhost:4000"

theme: minimal-mistakes-jekyll

# Minimal Mistakes Skin
# skins: default, dark, contrast, cyberpunk, ...
skin: default

# Markdown & Permalinks
markdown: kramdown
kramdown:
  input: GFM
permalink: /:title/

# Sass settings
sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
