# Titel der Website
title: Your Health Snapshot

# Theme: Name des Theme-Repository
theme: minimal-mistakes-jekyll

# Beschreibung (optional)
description: "Dies ist die Snapshot-Seite für Ihre Health-Lösung"

# Basis-URL für GitHub Pages, leer lassen, wenn Repository-Name gleich Benutzername ist
baseurl: ""

# URL der Website (GitHub Pages)
url: "https://HealthSolutionsHub.github.io/YourHealthSnapshot"

# Markdown-Einstellungen
markdown: kramdown

# Navigation
nav:
  - title: Startseite
    url: /
  - title: Fragebogen
    url: /questionnaire/   # <- hier nur Pfad zur Markdown-Seite
