# ---------------------------
# Minimaler Config für YourHealthSnapshot mit lokaler Minimal Mistakes Theme
# ---------------------------

title: Your Health Snapshot             # Название сайта
description: Health questionnaire      # Краткое описание сайта

url: "https://healthsolutionshub.github.io"  # GitHub Pages URL
baseurl: "/YourHealthSnapshot"              # Путь к репозиторию на GitHub Pages

markdown: kramdown

# Layout und Includes Pfade auf lokale Kopie der Theme setzen
defaults:
  - scope:
      path: ""       # Применяется ко всему репозиторию
    values:
      layout: single # Используем layout 'single' для страниц
