# Titel der Website
title: Your Health Snapshot

# Remote Theme korrekt mit exaktem Repo-Namen
remote_theme: HealthSolutionsHub/Minimal_Mistakes_Thema@main

# Beschreibung der Website
description: "Dies ist die Snapshot-Seite für Ihre Health-Lösung"

# Basis-URL für GitHub Pages
baseurl: ""

# URL der Website
url: "https://HealthSolutionsHub.github.io/YourHealthSnapshot"

# Markdown Einstellungen
markdown: kramdown

# Navigation für Seiten
nav:
  - title: Startseite
    url: /
  - title: Fragebogen
    url: /questionnaire/
